name: BasicSkyWars
main: HyperDevs\Main
author: HyperDevs
version: 1.0
api: 4.0.0
description: This plugin is made by ImAMadDev for HyperDevs Team

permissions:
  sw.creator:
    default: op
    description: 
