name: BasicSkyWars
main: AppGallery\Main
author: AppGallery
version: 1.0.2
api: 4.0.0
description: This plugin is made by ImAMadDev for AppGallery Team

permissions:
  sw.creator:
    default: op
    description: 
